Name            = "Mikhail"
Race            = "Dwarf"
HP	  			= "30"
Proficiency		= "2"
Strength 		= "16"
Dexterity 		= "10"
Constitution    = "14"
Intelligence 	= "8"
Wisdom 			= "8"
Charisma 		= "17"
Feats           = "War Caster,Polearm Master,Tavern Brawler,Tough,Spell Sniper,Great Weapon Master,Sharpshooter"
Items           = "Potion of Healing,Shortbow"
Class           = "Paladin|10|Oath of Ancients,Monk|10|Way of the Shadow"
Helmet          = "Leather Helmet"
Cloak           = "Leather Cloak"
Armor           = "Scale Mail"
Jewelery1       = "Bronze Ring"
Jewelery2       = "Bronze Ring"
Jewelery3       = "Bronze Ring"
Boots           = "Leather Boots"
Gloves          = "Leather Gloves"
MainHandWeapon  = "Rapier"
OffHandWeapon   = ""
