Name            = "Mikhail"
Race            = "Dwarf"
HP	  			= "30"
Proficiency		= "2"
Strength 		= "16"
Dexterity 		= "10"
Constitution    = "14"
Intelligence 	= "8"
Wisdom 			= "8"
Charisma 		= "17"
Feats           = "Warcaster,Polearm Master"
Items           = "Rapier,Shortbow"
Class           = "Paladin|3|Oath of Ancients"
