package main

var barbarianData = []ClassFeature{
	{Name: "Rage", Class: "Barbarian", Type: "NoChoice", SubClass: "Base", Level: 1, Options: "Rage"},
	{Name: "Unarmored Defense", Class: "Barbarian", Type: "NoChoice", SubClass: "Base", Level: 1, Options: "Unarmored Defense"},
	{Name: "Reckless Attack", Class: "Barbarian", Type: "NoChoice", SubClass: "Base", Level: 2, Options: "Reckless Attack"},
	{Name: "Danger Sense", Class: "Barbarian", Type: "NoChoice", SubClass: "Base", Level: 2, Options: "Danger Sense"},
	{Name: "Primal Knowledge", Class: "Barbarian", Type: "NoChoice", SubClass: "Base", Level: 2, Options: "Primal Knowledge"},
	{Name: "Frenzy", Class: "Barbarian", Type: "NoChoice", SubClass: "Path of the Berserker", Level: 3, Options: "Frenzy"},
	{Name: "Spirit Seeker", Class: "Barbarian", Type: "NoChoice", SubClass: "Path of the Totem Warrior", Level: 3, Options: "Spirit Seeker"},
	{Name: "Totem Spirit", Class: "Barbarian", Type: "NoChoice", SubClass: "Path of the Totem Warrior", Level: 3, Options: "Totem Spirit"},
	{Name: "Extra Attack", Class: "Barbarian", Type: "NoChoice", SubClass: "Base", Level: 5, Options: "Extra Attack"},
	{Name: "Fast Movement", Class: "Barbarian", Type: "NoChoice", SubClass: "Base", Level: 5, Options: "Fast Movement"},
	{Name: "Mindless Rage", Class: "Barbarian", Type: "NoChoice", SubClass: "Path of the Berserker", Level: 6, Options: "Mindless Rage"},
	{Name: "Aspect of the Beast", Class: "Barbarian", Type: "NoChoice", SubClass: "Path of the Totem Warrior", Level: 6, Options: "Aspect of the Beast"},
	{Name: "Feral Instinct", Class: "Barbarian", Type: "NoChoice", SubClass: "Base", Level: 7, Options: "Feral Instinct"},
	{Name: "Instinctive Pounce", Class: "Barbarian", Type: "NoChoice", SubClass: "Base", Level: 7, Options: "Instinctive Pounce"},
	{Name: "Brutal Critical", Class: "Barbarian", Type: "NoChoice", SubClass: "Base", Level: 9, Options: "Brutal Critical"},
	{Name: "Intimidating Presence", Class: "Barbarian", Type: "NoChoice", SubClass: "Path of the Berserker", Level: 10, Options: "Intimidating Presence"},
	{Name: "Spirit Walker", Class: "Barbarian", Type: "NoChoice", SubClass: "Path of the Totem Warrior", Level: 10, Options: "Spirit Walker"},
	{Name: "Relentless Rage", Class: "Barbarian", Type: "NoChoice", SubClass: "Base", Level: 11, Options: "Relentless Rage"},
	{Name: "Retaliation", Class: "Barbarian", Type: "NoChoice", SubClass: "Path of the Berserker", Level: 14, Options: "Retaliation"},
	{Name: "Totemic Attunement", Class: "Barbarian", Type: "NoChoice", SubClass: "Path of the Totem Warrior", Level: 14, Options: "Totemic Attunement"},
	{Name: "Persistent Rage", Class: "Barbarian", Type: "NoChoice", SubClass: "Base", Level: 15, Options: "Persistent Rage"},
	{Name: "Indomitable Might", Class: "Barbarian", Type: "NoChoice", SubClass: "Base", Level: 18, Options: "Indomitable Might"},
	{Name: "Primal Champion", Class: "Barbarian", Type: "NoChoice", SubClass: "Base", Level: 20, Options: "Primal Champion"},
}

var bardData = []ClassFeature{
	{Name: "Bardic Inspiration", Class: "Bard", Type: "NoChoice", SubClass: "Base", Level: 1, Options: "Bardic Inspiration"},
	{Name: "Jack of All Trades", Class: "Bard", Type: "NoChoice", SubClass: "Base", Level: 2, Options: "Jack of All Trades"},
	{Name: "Song of Rest", Class: "Bard", Type: "NoChoice", SubClass: "Base", Level: 2, Options: "Song of Rest"},
	{Name: "Magical Inspiration", Class: "Bard", Type: "NoChoice", SubClass: "Base", Level: 2, Options: "Magical Inspiration"},
	{Name: "Expertise", Class: "Bard", Type: "NoChoice", SubClass: "Base", Level: 3, Options: "Expertise"},
	{Name: "College of Lore Bard: Bonus Proficiencies", Class: "Bard", Type: "NoChoice", SubClass: "College of Lore", Level: 3, Options: "College of Lore Bard: Bonus Proficiencies"},
	{Name: "Cutting Words", Class: "Bard", Type: "NoChoice", SubClass: "College of Lore", Level: 3, Options: "Cutting Words"},
	{Name: "College of Valor Bard: Bonus Proficiencies", Class: "Bard", Type: "NoChoice", SubClass: "College of Valor", Level: 3, Options: "College of Valor Bard: Bonus Proficiencies"},
	{Name: "Combat Inspiration", Class: "Bard", Type: "NoChoice", SubClass: "College of Valor", Level: 3, Options: "Combat Inspiration"},
	{Name: "Font of Inspiration", Class: "Bard", Type: "NoChoice", SubClass: "Base", Level: 5, Options: "Font of Inspiration"},
	{Name: "Countercharm", Class: "Bard", Type: "NoChoice", SubClass: "Base", Level: 6, Options: "Countercharm"},
	{Name: "Additional Magical Secrets", Class: "Bard", Type: "NoChoice", SubClass: "College of Lore", Level: 6, Options: "Additional Magical Secrets"},
	{Name: "Extra Attack", Class: "Bard", Type: "NoChoice", SubClass: "Base", Level: 6, Options: "Extra Attack"},
	{Name: "Magical Secrets", Class: "Bard", Type: "NoChoice", SubClass: "Base", Level: 10, Options: "Magical Secrets"},
	{Name: "Peerless Skill", Class: "Bard", Type: "NoChoice", SubClass: "College of Lore", Level: 14, Options: "Peerless Skill"},
	{Name: "Battle Magic", Class: "Bard", Type: "NoChoice", SubClass: "College of Valor", Level: 14, Options: "Battle Magic"},
	{Name: "Superior Inspiration", Class: "Bard", Type: "NoChoice", SubClass: "Base", Level: 20, Options: "Superior Inspiration"},
}

var clericData = []ClassFeature{
	{Name: "Blessings of Knowledge", Class: "Cleric", Type: "NoChoice", SubClass: "Knowledge Domain", Level: 1, Options: "Blessings of Knowledge"},
	{Name: "Life Domain Cleric: Bonus Proficiencies", Class: "Cleric", Type: "NoChoice", SubClass: "Life Domain", Level: 1, Options: "Life Domain Cleric: Bonus Proficiencies"},
	{Name: "Disciple of Life", Class: "Cleric", Type: "NoChoice", SubClass: "Life Domain", Level: 1, Options: "Disciple of Life"},
	{Name: "Light Domain Cleric: Bonus Cantrip", Class: "Cleric", Type: "NoChoice", SubClass: "Light Domain", Level: 1, Options: "Light Domain Cleric: Bonus Cantrip"},
	{Name: "Warding Flare", Class: "Cleric", Type: "NoChoice", SubClass: "Light Domain", Level: 1, Options: "Warding Flare"},
	{Name: "Nature Domain Cleric: Bonus Proficiencies", Class: "Cleric", Type: "NoChoice", SubClass: "Nature Domain", Level: 1, Options: "Nature Domain Cleric: Bonus Proficiencies"},
	{Name: "Acolyte of Nature", Class: "Cleric", Type: "NoChoice", SubClass: "Nature Domain", Level: 1, Options: "Acolyte of Nature"},
	{Name: "Tempest Domain Cleric: Bonus Proficiencies", Class: "Cleric", Type: "NoChoice", SubClass: "Tempest Domain", Level: 1, Options: "Tempest Domain Cleric: Bonus Proficiencies"},
	{Name: "Wrath of the Storm", Class: "Cleric", Type: "NoChoice", SubClass: "Tempest Domain", Level: 1, Options: "Wrath of the Storm"},
	{Name: "Blessing of the Trickster", Class: "Cleric", Type: "NoChoice", SubClass: "Trickery Domain", Level: 1, Options: "Blessing of the Trickster"},
	{Name: "War Priest", Class: "Cleric", Type: "NoChoice", SubClass: "War Domain", Level: 1, Options: "War Priest"},
	{Name: "Channel Divinity: Turn Undead", Class: "Cleric", Type: "NoChoice", SubClass: "Base", Level: 2, Options: "Channel Divinity: Turn Undead"},
	{Name: "Channel Divinity: Knowledge of the Ages", Class: "Cleric", Type: "NoChoice", SubClass: "Knowledge Domain", Level: 2, Options: "Channel Divinity: Knowledge of the Ages"},
	{Name: "Channel Divinity: Radiance of the Dawn", Class: "Cleric", Type: "NoChoice", SubClass: "Life Domain", Level: 2, Options: "Channel Divinity: Radiance of the Dawn"},
	{Name: "Channel Divinity: Preserve Life", Class: "Cleric", Type: "NoChoice", SubClass: "Light Domain", Level: 2, Options: "Channel Divinity: Preserve Life"},
	{Name: "Channel Divinity: Charm Animals and Plants", Class: "Cleric", Type: "NoChoice", SubClass: "Nature Domain", Level: 2, Options: "Channel Divinity: Charm Animals and Plants"},
	{Name: "Channel Divinity: Destructive Wrath", Class: "Cleric", Type: "NoChoice", SubClass: "Tempest Domain", Level: 2, Options: "Channel Divinity: Destructive Wrath"},
	{Name: "Channel Divinity: Invoke Duplicity", Class: "Cleric", Type: "NoChoice", SubClass: "Trickery Domain", Level: 2, Options: "Channel Divinity: Invoke Duplicity"},
	{Name: "Channel Divinity: Guided Strike", Class: "Cleric", Type: "NoChoice", SubClass: "War Domain", Level: 2, Options: "Channel Divinity: Guided Strike"},
	{Name: "Harness Divine Power", Class: "Cleric", Type: "NoChoice", SubClass: "Base", Level: 2, Options: "Harness Divine Power"},
	{Name: "Destroy Undead", Class: "Cleric", Type: "NoChoice", SubClass: "Base", Level: 5, Options: "Destroy Undead"},
	{Name: "Channel Divinity: Read Thoughts", Class: "Cleric", Type: "NoChoice", SubClass: "Knowledge Domain", Level: 6, Options: "Channel Divinity: Read Thoughts"},
	{Name: "Blessed Healer", Class: "Cleric", Type: "NoChoice", SubClass: "Life Domain", Level: 6, Options: "Blessed Healer"},
	{Name: "Dampen Elements", Class: "Cleric", Type: "NoChoice", SubClass: "Nature Domain", Level: 6, Options: "Dampen Elements"},
	{Name: "Thunderous Strike", Class: "Cleric", Type: "NoChoice", SubClass: "Tempest Domain", Level: 6, Options: "Thunderous Strike"},
	{Name: "Channel Divinity: Cloak of Shadows", Class: "Cleric", Type: "NoChoice", SubClass: "Trickery Domain", Level: 6, Options: "Channel Divinity: Cloak of Shadows"},
	{Name: "Channel Divinity: War God's Blessing", Class: "Cleric", Type: "NoChoice", SubClass: "War Domain", Level: 6, Options: "Channel Divinity: War God's Blessing"},
	{Name: "Blessed Strikes", Class: "Cleric", Type: "NoChoice", SubClass: "Base", Level: 8, Options: "Blessed Strikes"},
	{Name: "Potent Spellcasting", Class: "Cleric", Type: "NoChoice", SubClass: "Knowledge Domain", Level: 8, Options: "Potent Spellcasting"},
	{Name: "Divine Strike", Class: "Cleric", Type: "NoChoice", SubClass: "Life Domain", Level: 8, Options: "Divine Strike"},
	{Name: "Potent Spellcasting", Class: "Cleric", Type: "NoChoice", SubClass: "Light Domain", Level: 8, Options: "Potent Spellcasting"},
	{Name: "Divine Strike", Class: "Cleric", Type: "NoChoice", SubClass: "Nature Domain", Level: 8, Options: "Divine Strike"},
	{Name: "Divine Strike", Class: "Cleric", Type: "NoChoice", SubClass: "Tempest Domain", Level: 8, Options: "Divine Strike"},
	{Name: "Divine Strike", Class: "Cleric", Type: "NoChoice", SubClass: "Trickery Domain", Level: 8, Options: "Divine Strike"},
	{Name: "Divine Strike", Class: "Cleric", Type: "NoChoice", SubClass: "War Domain", Level: 8, Options: "Divine Strike"},
	{Name: "Divine Intervention", Class: "Cleric", Type: "NoChoice", SubClass: "Base", Level: 10, Options: "Divine Intervention"},
	{Name: "Visions of the Past", Class: "Cleric", Type: "NoChoice", SubClass: "Knowledge Domain", Level: 17, Options: "Visions of the Past"},
	{Name: "Supreme Healing", Class: "Cleric", Type: "NoChoice", SubClass: "Life Domain", Level: 17, Options: "Supreme Healing"},
	{Name: "Corona of Light", Class: "Cleric", Type: "NoChoice", SubClass: "Light Domain", Level: 17, Options: "Corona of Light"},
	{Name: "Master of Nature", Class: "Cleric", Type: "NoChoice", SubClass: "Nature Domain", Level: 17, Options: "Master of Nature"},
	{Name: "Stormborn", Class: "Cleric", Type: "NoChoice", SubClass: "Tempest Domain", Level: 17, Options: "Stormborn"},
	{Name: "Improved Duplicity", Class: "Cleric", Type: "NoChoice", SubClass: "Trickery Domain", Level: 17, Options: "Improved Duplicity"},
	{Name: "Avatar of Battle", Class: "Cleric", Type: "NoChoice", SubClass: "War Domain", Level: 17, Options: "Avatar of Battle"},
}

var fighterData = []ClassFeature{
	{Name: "Second Wind", Class: "Fighter", Type: "NoChoice", SubClass: "Base", Level: 1, Options: "Second Wind"},
	{Name: "Action Surge", Class: "Fighter", Type: "NoChoice", SubClass: "Base", Level: 1, Options: "Action Surge"},
	{Name: "Fighting Style", Class: "Fighter", Type: "NoChoice", SubClass: "Base", Level: 1, Options: "Fighting Style"},
	{Name: "Improved Critical", Class: "Fighter", Type: "NoChoice", SubClass: "Champion", Level: 3, Options: "Improved Critical"},
	{Name: "Combat Superiority", Class: "Fighter", Type: "NoChoice", SubClass: "Battle Master", Level: 3, Options: "Combat Superiority"},
	{Name: "Student of War", Class: "Fighter", Type: "NoChoice", SubClass: "Battle Master", Level: 3, Options: "Student of War"},
	{Name: "Weapon Bond", Class: "Fighter", Type: "NoChoice", SubClass: "Eldritch Knight", Level: 3, Options: "Weapon Bond"},
	{Name: "Extra Attack", Class: "Fighter", Type: "NoChoice", SubClass: "Base", Level: 5, Options: "Extra Attack"},
	{Name: "Remarkable Athlete", Class: "Fighter", Type: "NoChoice", SubClass: "Champion", Level: 7, Options: "Remarkable Athlete"},
	{Name: "Know Your Enemy", Class: "Fighter", Type: "NoChoice", SubClass: "Battle Master", Level: 7, Options: "Know Your Enemy"},
	{Name: "War Magic", Class: "Fighter", Type: "NoChoice", SubClass: "Eldritch Knight", Level: 7, Options: "War Magic"},
	{Name: "Indomitable", Class: "Fighter", Type: "NoChoice", SubClass: "Base", Level: 9, Options: "Indomitable"},
	{Name: "Additional Fighting Style", Class: "Fighter", Type: "NoChoice", SubClass: "Champion", Level: 10, Options: "Additional Fighting Style"},
	{Name: "Eldritch Strike", Class: "Fighter", Type: "NoChoice", SubClass: "Eldritch Knight", Level: 10, Options: "Eldritch Strike"},
	{Name: "Superior Critical", Class: "Fighter", Type: "NoChoice", SubClass: "Champion", Level: 15, Options: "Superior Critical"},
	{Name: "Relentless", Class: "Fighter", Type: "NoChoice", SubClass: "Battle Master", Level: 15, Options: "Relentless"},
	{Name: "Arcane Charge", Class: "Fighter", Type: "NoChoice", SubClass: "Eldritch Knight", Level: 15, Options: "Arcane Charge"},
	{Name: "Survivor", Class: "Fighter", Type: "NoChoice", SubClass: "Champion", Level: 18, Options: "Survivor"},
}

var paladinData = []ClassFeature{
	{Name: "Divine Sense", Class: "Paladin", Type: "NoChoice", SubClass: "Base", Level: 1, Options: "Divine Sense"},
	{Name: "Lay on Hands", Class: "Paladin", Type: "NoChoice", SubClass: "Base", Level: 1, Options: "Lay on Hands"},
	{Name: "Divine Smite", Class: "Paladin", Type: "NoChoice", SubClass: "Base", Level: 2, Options: "Divine Smite"},
	{Name: "Divine Health", Class: "Paladin", Type: "NoChoice", SubClass: "Base", Level: 3, Options: "Divine Heatlh"},
	{Name: "Channel Divinity", Class: "Paladin", Type: "NoChoice", SubClass: "Oath of the Ancients", Level: 3, Options: "Nature's Wrath|Turn the Faithless"},
	{Name: "Channel Divinity", Class: "Paladin", Type: "NoChoice", SubClass: "Oath of the Devotion", Level: 3, Options: "Sacred Weapon|Turn the Unholy"},
	{Name: "Channel Divinity", Class: "Paladin", Type: "NoChoice", SubClass: "Oath of the Vengeance", Level: 3, Options: "Abjure Enemy|Vow of Enmity"},
	{Name: "Harness Divine Power", Class: "Paladin", Type: "NoChoice", SubClass: "Base", Level: 3, Options: "Harness Divine Power"},
	{Name: "Extra Attack", Class: "Paladin", Type: "NoChoice", SubClass: "Base", Level: 5, Options: "Extra Attack"},
	{Name: "Aura of Protection", Class: "Paladin", Type: "NoChoice", SubClass: "Base", Level: 6, Options: "Aura of Protection"},
	{Name: "Aura of Warding", Class: "Paladin", Type: "NoChoice", SubClass: "Oath of the Ancients", Level: 7, Options: "Aura of Warding"},
	{Name: "Aura of Devotion", Class: "Paladin", Type: "NoChoice", SubClass: "Oath of the Devotion", Level: 7, Options: "Aura of Devotion"},
	{Name: "Relentless Avenger", Class: "Paladin", Type: "NoChoice", SubClass: "Oath of the Vengeance", Level: 7, Options: "Relentless Avenger"},
	{Name: "Aura of Courage", Class: "Paladin", Type: "NoChoice", SubClass: "Base", Level: 10, Options: "Aura of Courage"},
	{Name: "Improved Divine Smite", Class: "Paladin", Type: "NoChoice", SubClass: "Base", Level: 11, Options: "Improved Divine Smite"},
	{Name: "Cleansing Touch", Class: "Paladin", Type: "NoChoice", SubClass: "Base", Level: 14, Options: "Cleansing Touch"},
	{Name: "Undying Sentinel", Class: "Paladin", Type: "NoChoice", SubClass: "Oath of the Ancients", Level: 15, Options: "Undying Sentinel"},
	{Name: "Purity of Spirit", Class: "Paladin", Type: "NoChoice", SubClass: "Oath of the Devotion", Level: 15, Options: "Purity of Spirit"},
	{Name: "Soul of Vengeance", Class: "Paladin", Type: "NoChoice", SubClass: "Oath of the Vengeance", Level: 15, Options: "Soul of Vengeance"},
	{Name: "Elder Champion", Class: "Paladin", Type: "NoChoice", SubClass: "Oath of the Ancients", Level: 20, Options: "Elder Champion"},
	{Name: "Holy Nimbus", Class: "Paladin", Type: "NoChoice", SubClass: "Oath of the Devotion", Level: 20, Options: "Holy Nimbus"},
	{Name: "Avenging Angel", Class: "Paladin", Type: "NoChoice", SubClass: "Oath of the Vengeance", Level: 20, Options: "Avenging Angel"},
}

var monkData = []ClassFeature{
	{Name: "Unarmored Defense", Class: "Monk", Type: "NoChoice", SubClass: "Base", Level: 1, Options: "Unarmored Defense"},
	{Name: "Martial Arts", Class: "Monk", Type: "NoChoice", SubClass: "Base", Level: 1, Options: "Martial Arts"},
	{Name: "Ki", Class: "Monk", Type: "NoChoice", SubClass: "Base", Level: 2, Options: "Ki"},
	{Name: "Flurry of Blows", Class: "Monk", Type: "NoChoice", SubClass: "Base", Level: 2, Options: "Flurry of Blows"},
	{Name: "Patient Defense", Class: "Monk", Type: "NoChoice", SubClass: "Base", Level: 2, Options: "Patient Defense"},
	{Name: "Step of the Wind", Class: "Monk", Type: "NoChoice", SubClass: "Base", Level: 2, Options: "Step of the Wind"},
	{Name: "Unarmored Movement", Class: "Monk", Type: "NoChoice", SubClass: "Base", Level: 2, Options: "Unarmored Movement"},
	{Name: "Dedicated Weapon", Class: "Monk", Type: "NoChoice", SubClass: "Base", Level: 2, Options: "Dedicated Weapon"},
	{Name: "Deflect Missiles", Class: "Monk", Type: "NoChoice", SubClass: "Base", Level: 3, Options: "Deflect Missiles"},
	{Name: "Ki-Fueled Attack", Class: "Monk", Type: "NoChoice", SubClass: "Base", Level: 3, Options: "Ki-Fueled Attack"},
	{Name: "Open Hand Technique", Class: "Monk", Type: "NoChoice", SubClass: "Way of the Open Hand", Level: 3, Options: "Open Hand Technique"},
	{Name: "Shadow Arts", Class: "Monk", Type: "NoChoice", SubClass: "Way of the Shadow", Level: 3, Options: "Shadow Arts"},
	{Name: "Disciple of the Elements", Class: "Monk", Type: "NoChoice", SubClass: "Way of the Four Elements", Level: 3, Options: "Disciple of the Elements"},
	{Name: "Slow Fall", Class: "Monk", Type: "NoChoice", SubClass: "Base", Level: 4, Options: "Slow Fall"},
	{Name: "Quickened Healing", Class: "Monk", Type: "NoChoice", SubClass: "Base", Level: 4, Options: "Quickened Healing"},
	{Name: "Extra Attack", Class: "Monk", Type: "NoChoice", SubClass: "Base", Level: 5, Options: "Extra Attack"},
	{Name: "Stunning Strike", Class: "Monk", Type: "NoChoice", SubClass: "Base", Level: 5, Options: "Stunning Strike"},
	{Name: "Focused Aim", Class: "Monk", Type: "NoChoice", SubClass: "Base", Level: 5, Options: "Focused Aim"},
	{Name: "Ki-Empowered Strikes", Class: "Monk", Type: "NoChoice", SubClass: "Base", Level: 6, Options: "Ki-Empowered Strikes"},
	{Name: "Wholeness of Body", Class: "Monk", Type: "NoChoice", SubClass: "Way of the Open Hand", Level: 6, Options: "Wholeness of Body"},
	{Name: "Shadow Step", Class: "Monk", Type: "NoChoice", SubClass: "Way of the Shadow", Level: 6, Options: "Shadow Step"},
	{Name: "Evasion", Class: "Monk", Type: "NoChoice", SubClass: "Base", Level: 7, Options: "Evasion"},
	{Name: "Stillness of Mind", Class: "Monk", Type: "NoChoice", SubClass: "Base", Level: 7, Options: "Stillness of Mind"},
	{Name: "Purity of Body", Class: "Monk", Type: "NoChoice", SubClass: "Base", Level: 10, Options: "Purity of Body"},
	{Name: "Tranquility", Class: "Monk", Type: "NoChoice", SubClass: "Way of the Open Hand", Level: 11, Options: "Tranquility"},
	{Name: "Cloak of Shadows", Class: "Monk", Type: "NoChoice", SubClass: "Way of the Shadow", Level: 11, Options: "Cloak of Shadows"},
	{Name: "Tongue of the Sun and Moon", Class: "Monk", Type: "NoChoice", SubClass: "Base", Level: 13, Options: "Tongue of the Sun and Moon"},
	{Name: "Diamond Soul", Class: "Monk", Type: "NoChoice", SubClass: "Base", Level: 14, Options: "Diamond Soul"},
	{Name: "Timeless Body", Class: "Monk", Type: "NoChoice", SubClass: "Base", Level: 15, Options: "Monk: Timeless Body"},
	{Name: "Monk: Quivering Palm", Class: "Monk", Type: "NoChoice", SubClass: "Way of the Open Hand", Level: 17, Options: "Quivering Palm"},
	{Name: "Opportunist", Class: "Monk", Type: "NoChoice", SubClass: "Way of the Shadow", Level: 17, Options: "Opportunist"},
	{Name: "Empty Body", Class: "Monk", Type: "NoChoice", SubClass: "Base", Level: 18, Options: "Empty Body"},
	{Name: "Perfect Self", Class: "Monk", Type: "NoChoice", SubClass: "Base", Level: 18, Options: "Perfect Self"},
}

var druidData = []ClassFeature{
	{Name: "Wild Shape", Class: "Druid", Type: "NoChoice", SubClass: "Base", Level: 2, Options: "Wild Shape"},
	{Name: "Wild Companion", Class: "Druid", Type: "NoChoice", SubClass: "Base", Level: 2, Options: "Wild Companion"},
	{Name: "Circle of the Land Druid: Bonus Cantrip", Class: "Druid", Type: "NoChoice", SubClass: "Circle of the Land", Level: 2, Options: "Circle of the Land Druid: Bonus Cantrip"},
	{Name: "Natural Recovery", Class: "Druid", Type: "NoChoice", SubClass: "Circle of the Land", Level: 2, Options: "Natural Recovery"},
	{Name: "Combat Wild Shape", Class: "Druid", Type: "NoChoice", SubClass: "Circle of the Moon", Level: 2, Options: "Combat Wild Shape"},
	{Name: "Circle Spells", Class: "Druid", Type: "NoChoice", SubClass: "Circle of the Land", Level: 3, Options: "Circle Spells"},
	{Name: "Circle Forms", Class: "Druid", Type: "NoChoice", SubClass: "Circle of the Land", Level: 3, Options: "Circle Forms"},
	{Name: "Land's Stride", Class: "Druid", Type: "NoChoice", SubClass: "Circle of the Land", Level: 6, Options: "Land's Stride"},
	{Name: "Primal Strike", Class: "Druid", Type: "NoChoice", SubClass: "Circle of the Moon", Level: 6, Options: "Primal Strike"},
	{Name: "Nature's Ward", Class: "Druid", Type: "NoChoice", SubClass: "Circle of the Land", Level: 10, Options: "Nature's Ward"},
	{Name: "Elemental Wild Shape", Class: "Druid", Type: "NoChoice", SubClass: "Circle of the Moon", Level: 10, Options: "Elemental Wild Shape"},
	{Name: "Nature's Sanctuary", Class: "Druid", Type: "NoChoice", SubClass: "Circle of the Land", Level: 14, Options: "Nature's Sanctuary"},
	{Name: "Thousand Forms", Class: "Druid", Type: "NoChoice", SubClass: "Circle of the Moon", Level: 14, Options: "Thousand Forms"},
	{Name: "Druid: Timeless Body", Class: "Druid", Type: "NoChoice", SubClass: "Base", Level: 18, Options: "Druid: Timeless Body"},
	{Name: "Beast Spells", Class: "Druid", Type: "NoChoice", SubClass: "Base", Level: 18, Options: "Beast Spells"},
	{Name: "Archdruid", Class: "Druid", Type: "NoChoice", SubClass: "Base", Level: 20, Options: "Archdruid"},
}

var rangerData = []ClassFeature{
	{Name: "Favored Opponent", Type: "Choice", Class: "Ranger", SubClass: "Base", Level: 1, Options: "Favored Enemy|Favored Foe"},
	{Name: "Explorer", Type: "Choice", Class: "Ranger", SubClass: "Base", Level: 2, Options: "Natural Explorer|Deft Explorer"},
	{Name: "Awareness", Type: "Choice", Class: "Ranger", SubClass: "Base", Level: 3, Options: "Primeval Awareness|Primal Awareness"},
	{Name: "Hunter's Prey", Type: "NoChoice", Class: "Ranger", SubClass: "Hunter", Level: 3, Options: "Hunter's Prey"},
	{Name: "Companion", Type: "NoChoice", Class: "Ranger", SubClass: "Beast Master", Level: 3, Options: "Ranger's Companion|Primal Companion"},
	{Name: "Extra Attack", Type: "NoChoice", Class: "Ranger", SubClass: "Base", Level: 5, Options: "Extra Attack"},
	{Name: "Defensive Tactics", Type: "NoChoice", Class: "Ranger", SubClass: "Hunter", Level: 7, Options: "Defensive Tactics"},
	{Name: "Exceptional Training", Type: "NoChoice", Class: "Ranger", SubClass: "Beast Master", Level: 7, Options: "Exceptional Training"},
	{Name: "Land's Stride", Type: "NoChoice", Class: "Ranger", SubClass: "Base", Level: 8, Options: "Land's Stride"},
	{Name: "Hiding", Type: "Choice", Class: "Ranger", SubClass: "Base", Level: 10, Options: "Hide in Plain Sight|Nature's Veil"},
	{Name: "Multiattack", Type: "NoChoice", Class: "Ranger", SubClass: "Hunter", Level: 11, Options: "Multiattack"},
	{Name: "Bestial Fury", Type: "NoChoice", Class: "Ranger", SubClass: "Beast Master", Level: 11, Options: "Bestial Fury"},
	{Name: "Vanish", Type: "NoChoice", Class: "Ranger", SubClass: "Base", Level: 10, Options: "Vanish"},
	{Name: "Superior Hunter's Defense", Type: "NoChoice", Class: "Ranger", SubClass: "Hunter", Level: 15, Options: "Superior Hunter's Defense"},
	{Name: "Share Spells", Type: "NoChoice", Class: "Ranger", SubClass: "Beast Master", Level: 15, Options: "Share Spells"},
	{Name: "Feral Senses", Type: "NoChoice", Class: "Ranger", SubClass: "Base", Level: 18, Options: "Feral Senses"},
	{Name: "Foe Slayer", Type: "NoChoice", Class: "Ranger", SubClass: "Base", Level: 18, Options: "Foe Slayer"},
}

var rogueData = []ClassFeature{
	{Name: "Expertise", Class: "Rogue", Type: "NoChoice", SubClass: "Base", Level: 1, Options: "Expertise"},
	{Name: "Sneak Attack", Class: "Rogue", Type: "NoChoice", SubClass: "Base", Level: 1, Options: "Sneak Attack"},
	{Name: "Thieves' Cant", Class: "Rogue", Type: "NoChoice", SubClass: "Base", Level: 1, Options: "Thieves' Cant"},
	{Name: "Cunning Action", Class: "Rogue", Type: "NoChoice", SubClass: "Base", Level: 2, Options: "Cunning Action"},
	{Name: "Steady Aim", Class: "Rogue", Type: "NoChoice", SubClass: "Base", Level: 3, Options: "Steady Aim"},
	{Name: "Fast Hands", Class: "Rogue", Type: "NoChoice", SubClass: "Thief", Level: 3, Options: "Fast Hands"},
	{Name: "Second-Story Work", Class: "Rogue", Type: "NoChoice", SubClass: "Thief", Level: 3, Options: "Second-Story Work"},
	{Name: "Assassinate", Class: "Rogue", Type: "NoChoice", SubClass: "Assassin", Level: 3, Options: "Assassinate"},
	{Name: "Mage Hand Legerdemain", Class: "Rogue", Type: "NoChoice", SubClass: "Arcane Trickster", Level: 3, Options: "Mage Hand Legerdemain"},
	{Name: "Uncanny Dodge", Class: "Rogue", Type: "NoChoice", SubClass: "Base", Level: 5, Options: "Uncanny Dodge"},
	{Name: "Evasion", Class: "Rogue", Type: "NoChoice", SubClass: "Base", Level: 7, Options: "Evasion"},
	{Name: "Supreme Sneak", Class: "Rogue", Type: "NoChoice", SubClass: "Thief", Level: 9, Options: "Supreme Sneak"},
	{Name: "Infiltration Expertise", Class: "Rogue", Type: "NoChoice", SubClass: "Assassin", Level: 9, Options: "Infiltration Expertise"},
	{Name: "Magical Ambush", Class: "Rogue", Type: "NoChoice", SubClass: "Fast Hands", Level: 9, Options: "Magical Ambush"},
	{Name: "Reliable Talent", Class: "Rogue", Type: "NoChoice", SubClass: "Base", Level: 11, Options: "Reliable Talent"},
	{Name: "Use Magic Device", Class: "Rogue", Type: "NoChoice", SubClass: "Thief", Level: 13, Options: "Use Magic Device"},
	{Name: "Impostor", Class: "Rogue", Type: "NoChoice", SubClass: "Assassin", Level: 13, Options: "Impostor"},
	{Name: "Versatile Trickster", Class: "Rogue", Type: "NoChoice", SubClass: "Arcane Trickster", Level: 13, Options: "Versatile Trickster"},
	{Name: "Blindsense", Class: "Rogue", Type: "NoChoice", SubClass: "Base", Level: 14, Options: "Blindsense"},
	{Name: "Slippery Mind", Class: "Rogue", Type: "NoChoice", SubClass: "Base", Level: 15, Options: "Slippery Mind"},
	{Name: "Thief's Reflexes", Class: "Rogue", Type: "NoChoice", SubClass: "Thief", Level: 17, Options: "Thief's Reflexes"},
	{Name: "Death Strike", Class: "Rogue", Type: "NoChoice", SubClass: "Assassin", Level: 17, Options: "Death Strike"},
	{Name: "Spell Thief", Class: "Rogue", Type: "NoChoice", SubClass: "Arcane Trickster", Level: 17, Options: "Spell Thief"},
	{Name: "Elusive", Class: "Rogue", Type: "NoChoice", SubClass: "Base", Level: 18, Options: "Elusive"},
	{Name: "Stroke of Luck", Class: "Rogue", Type: "NoChoice", SubClass: "Base", Level: 18, Options: "Stroke of Luck"},
}

var sorcererData = []ClassFeature{
	{Name: "Dragon Ancestor", Class: "Sorcerer", Type: "NoChoice", SubClass: "Draconic Bloodline", Level: 1, Options: "Dragon Ancestor"},
	{Name: "Draconic Resilience", Class: "Sorcerer", Type: "NoChoice", SubClass: "Draconic Bloodline", Level: 1, Options: "Draconic Resilience"},
	{Name: "Wild Magic Surge", Class: "Sorcerer", Type: "NoChoice", SubClass: "Wild Magic", Level: 1, Options: "Wild Magic Surge"},
	{Name: "Tides of Chaos", Class: "Sorcerer", Type: "NoChoice", SubClass: "Wild Magic", Level: 1, Options: "Tides of Chaos"},
	{Name: "Font of Magic", Class: "Sorcerer", Type: "NoChoice", SubClass: "Base", Level: 2, Options: "Font of Magic"},
	{Name: "Metamagic", Class: "Sorcerer", Type: "NoChoice", SubClass: "Base", Level: 3, Options: "Metamagic"},
	{Name: "Magical Guidance", Class: "Sorcerer", Type: "NoChoice", SubClass: "Base", Level: 5, Options: "Magical Guidance"},
	{Name: "Elemental Affinity", Class: "Sorcerer", Type: "NoChoice", SubClass: "Draconic Bloodline", Level: 6, Options: "Elemental Affinity"},
	{Name: "Bend Luck", Class: "Sorcerer", Type: "NoChoice", SubClass: "Wild Magic", Level: 6, Options: "Bend Luck"},
	{Name: "Dragon Wings", Class: "Sorcerer", Type: "NoChoice", SubClass: "Draconic Bloodline", Level: 14, Options: "Dragon Wings"},
	{Name: "Controlled Chaos", Class: "Sorcerer", Type: "NoChoice", SubClass: "Wild Magic", Level: 14, Options: "Controlled Chaos"},
	{Name: "Draconic Presence", Class: "Sorcerer", Type: "NoChoice", SubClass: "Draconic Bloodline", Level: 18, Options: "Draconic Presence"},
	{Name: "Spell Bombardment", Class: "Sorcerer", Type: "NoChoice", SubClass: "Wild Magic", Level: 18, Options: "Spell Bombardment"},
	{Name: "Sorcerous Restoration", Class: "Sorcerer", Type: "NoChoice", SubClass: "Base", Level: 20, Options: "Sorcerous Restoration"},
}

var warlockData = []ClassFeature{
	{Name: "Fey Presence", Class: "Warlock", Type: "NoChoice", SubClass: "The Archfey", Level: 1, Options: "Fey Presence"},
	{Name: "Dark One's Blessing", Class: "Warlock", Type: "NoChoice", SubClass: "The Fiend", Level: 1, Options: "Dark One's Blessing"},
	{Name: "Awakened Mind", Class: "Warlock", Type: "NoChoice", SubClass: "The Great Old One", Level: 1, Options: "Awakened Mind"},
	{Name: "Eldritch Invocations", Class: "Warlock", Type: "NoChoice", SubClass: "Base", Level: 1, Options: "Eldritch Invocations"},
	{Name: "Pact Boon", Class: "Warlock", Type: "NoChoice", SubClass: "Base", Level: 3, Options: "Pact Boon"},
	{Name: "Misty Escape", Class: "Warlock", Type: "NoChoice", SubClass: "The Archfey", Level: 6, Options: "Misty Escape"},
	{Name: "Dark One's Own Luck", Class: "Warlock", Type: "NoChoice", SubClass: "The Fiend", Level: 6, Options: "Dark One's Own Luck"},
	{Name: "Entropic Ward", Class: "Warlock", Type: "NoChoice", SubClass: "The Great Old One", Level: 6, Options: "Entropic Ward"},
	{Name: "Mystic Arcanum", Class: "Warlock", Type: "NoChoice", SubClass: "Base", Level: 10, Options: "Mystic Arcanum"},
	{Name: "Beguiling Defenses", Class: "Warlock", Type: "NoChoice", SubClass: "The Archfey", Level: 10, Options: "Beguiling Defenses: Reverse Charm|Beguiling Defenses: Charm Immunity"},
	{Name: "Fiendish Resilience", Class: "Warlock", Type: "NoChoice", SubClass: "The Fiend", Level: 10, Options: "Fiendish Resilience"},
	{Name: "Thought Shield", Class: "Warlock", Type: "NoChoice", SubClass: "The Great Old One", Level: 10, Options: "Thought Shield"},
	{Name: "Dark Delirium", Class: "Warlock", Type: "NoChoice", SubClass: "The Archfey", Level: 14, Options: "Dark Delirium"},
	{Name: "Hurl Through Hell", Class: "Warlock", Type: "NoChoice", SubClass: "The Fiend", Level: 14, Options: "Hurl Through Hell"},
	{Name: "Create Thrall", Class: "Warlock", Type: "NoChoice", SubClass: "The Great Old One", Level: 14, Options: "Create Thrall"},
	{Name: "Eldritch Master", Class: "Warlock", Type: "NoChoice", SubClass: "The Archfey", Level: 20, Options: "Eldritch Master"},
}

var wizardData = []ClassFeature{
	{Name: "Arcane Recovery", Class: "Wizard", Type: "NoChoice", SubClass: "Base", Level: 1, Options: "Arcane Recovery"},
	{Name: "Abjuration Savant", Class: "Wizard", Type: "NoChoice", SubClass: "School of Abjuration", Level: 2, Options: "Abjuration Savant"},
	{Name: "Arcane Ward", Class: "Wizard", Type: "NoChoice", SubClass: "School of Abjuration", Level: 2, Options: "Arcane Ward"},
	{Name: "Conjuration Savant", Class: "Wizard", Type: "NoChoice", SubClass: "School of Conjuration", Level: 2, Options: "Conjuration Savant"},
	{Name: "Minor Conjuration", Class: "Wizard", Type: "NoChoice", SubClass: "School of Conjuration", Level: 2, Options: "Minor Conjuration"},
	{Name: "Divination Savant", Class: "Wizard", Type: "NoChoice", SubClass: "School of Divination", Level: 2, Options: "Divination Savant"},
	{Name: "Portent", Class: "Wizard", Type: "NoChoice", SubClass: "School of Divination", Level: 2, Options: "Portent"},
	{Name: "Enchantment Savant", Class: "Wizard", Type: "NoChoice", SubClass: "School of Enchantment", Level: 2, Options: "Enchantment Savant"},
	{Name: "Hypnotic Gaze", Class: "Wizard", Type: "NoChoice", SubClass: "School of Enchantment", Level: 2, Options: "Hypnotic Gaze"},
	{Name: "Evocation Savant", Class: "Wizard", Type: "NoChoice", SubClass: "School of Evocation", Level: 2, Options: "Evocation Savant"},
	{Name: "Sculpt Spells", Class: "Wizard", Type: "NoChoice", SubClass: "School of Evocation", Level: 2, Options: "Sculpt Spells"},
	{Name: "Illusion Savant", Class: "Wizard", Type: "NoChoice", SubClass: "School of Illusion", Level: 2, Options: "Illusion Savant"},
	{Name: "Improved Minor Illusion", Class: "Wizard", Type: "NoChoice", SubClass: "School of Illusion", Level: 2, Options: "Improved Minor Illusion"},
	{Name: "Necromancy Savant", Class: "Wizard", Type: "NoChoice", SubClass: "School of Necromancy", Level: 2, Options: "Necromancy Savant"},
	{Name: "Grim Harvest", Class: "Wizard", Type: "NoChoice", SubClass: "School of Necromancy", Level: 2, Options: "Grim Harvest"},
	{Name: "Transmutation Savant", Class: "Wizard", Type: "NoChoice", SubClass: "School of Transmutation", Level: 2, Options: "Transmutation Savant"},
	{Name: "Minor Alchemy", Class: "Wizard", Type: "NoChoice", SubClass: "School of Transmutation", Level: 2, Options: "Minor Alchemy"},
	{Name: "Cantrip Formulas", Class: "Wizard", Type: "NoChoice", SubClass: "Base", Level: 3, Options: "Cantrip Formulas"},
	{Name: "Projected Ward", Class: "Wizard", Type: "NoChoice", SubClass: "School of Abjuration", Level: 6, Options: "Projected Ward"},
	{Name: "Benign Transportation", Class: "Wizard", Type: "NoChoice", SubClass: "School of Conjuration", Level: 6, Options: "Benign Transportation"},
	{Name: "Expert Divination", Class: "Wizard", Type: "NoChoice", SubClass: "School of Divination", Level: 6, Options: "Expert Divination"},
	{Name: "Instinctive Charm", Class: "Wizard", Type: "NoChoice", SubClass: "School of Enchantment", Level: 6, Options: "Instinctive Charm"},
	{Name: "Potent Cantrip", Class: "Wizard", Type: "NoChoice", SubClass: "School of Evocation", Level: 6, Options: "Potent Cantrip"},
	{Name: "Malleable Illusions", Class: "Wizard", Type: "NoChoice", SubClass: "School of Illusion", Level: 6, Options: "Malleable Illusions"},
	{Name: "Undead Thralls", Class: "Wizard", Type: "NoChoice", SubClass: "School of Necromancy", Level: 6, Options: "Undead Thralls"},
	{Name: "Transmuter's Stone", Class: "Wizard", Type: "NoChoice", SubClass: "School of Transmutation", Level: 6, Options: "Transmuter's Stone"},
	{Name: "Improved Abjuration", Class: "Wizard", Type: "NoChoice", SubClass: "School of Abjuration", Level: 10, Options: "Improved Abjuration"},
	{Name: "Focused Conjuration", Class: "Wizard", Type: "NoChoice", SubClass: "School of Conjuration", Level: 10, Options: "Focused Conjuration"},
	{Name: "The Third Eye", Class: "Wizard", Type: "NoChoice", SubClass: "School of Divination", Level: 10, Options: "The Third Eye"},
	{Name: "Split Enchantment", Class: "Wizard", Type: "NoChoice", SubClass: "School of Enchantment", Level: 10, Options: "Split Enchantment"},
	{Name: "Empowered Evocation", Class: "Wizard", Type: "NoChoice", SubClass: "School of Evocation", Level: 10, Options: "Empowered Evocation"},
	{Name: "Illusory Self", Class: "Wizard", Type: "NoChoice", SubClass: "School of Illusion", Level: 10, Options: "Illusory Self"},
	{Name: "Inured to Undeath", Class: "Wizard", Type: "NoChoice", SubClass: "School of Necromancy", Level: 10, Options: "Inured to Undeath"},
	{Name: "Shapechanger", Class: "Wizard", Type: "NoChoice", SubClass: "School of Transmutation", Level: 10, Options: "Shapechanger"},
	{Name: "Spell Resistance", Class: "Wizard", Type: "NoChoice", SubClass: "School of Abjuration", Level: 14, Options: "Spell Resistance"},
	{Name: "Durable Summons", Class: "Wizard", Type: "NoChoice", SubClass: "School of Conjuration", Level: 14, Options: "Durable Summons"},
	{Name: "Greater Portent", Class: "Wizard", Type: "NoChoice", SubClass: "School of Divination", Level: 14, Options: "Greater Portent"},
	{Name: "Alter Memories", Class: "Wizard", Type: "NoChoice", SubClass: "School of Enchantment", Level: 14, Options: "Alter Memories"},
	{Name: "Overchannel", Class: "Wizard", Type: "NoChoice", SubClass: "School of Evocation", Level: 14, Options: "Overchannel"},
	{Name: "Illusory Reality", Class: "Wizard", Type: "NoChoice", SubClass: "School of Illusion", Level: 14, Options: "Illusory Reality"},
	{Name: "Command Undead", Class: "Wizard", Type: "NoChoice", SubClass: "School of Necromancy", Level: 14, Options: "Command Undead"},
	{Name: "Master Transmuter", Class: "Wizard", Type: "NoChoice", SubClass: "School of Transmutation", Level: 14, Options: "Master Transmuter"},
	{Name: "Spell Mastery", Class: "Wizard", Type: "NoChoice", SubClass: "Base", Level: 18, Options: "Spell Mastery"},
	{Name: "Signature Spells", Class: "Wizard", Type: "NoChoice", SubClass: "Base", Level: 20, Options: "Signature Spells"},
}

var classFeatures = [][]ClassFeature{
	barbarianData,
	bardData,
	clericData,
	druidData,
	fighterData,
	monkData,
	paladinData,
	rangerData,
	rogueData,
	sorcererData,
	warlockData,
	wizardData,
}
