package main

var armorData = []Item{
	{Name: "None", Category: "Armor", Type: "Helmet", Description: ""},
	{Name: "None", Category: "Armor", Type: "Jewelery", Description: ""},
	{Name: "None", Category: "Armor", Type: "Cloak", Description: ""},
	{Name: "None", Category: "Armor", Type: "Boots", Description: ""},
	{Name: "None", Category: "Armor", Type: "Gloves", Description: ""},
	{Name: "None", Category: "Armor", Type: "Armor", Description: ""},
	{Name: "None", Category: "Armor", Type: "Helmet", Description: ""},
	{Name: "Leather Helmet", Category: "Armor", Type: "Helmet", Description: "A leather helmet."},
	{Name: "Bronze Ring", Category: "Armor", Type: "Jewelery", Description: "A bronze ring."},
	{Name: "Leather Cloak", Category: "Armor", Type: "Cloak", Description: "A leather cloak."},
	{Name: "Leather Boots", Category: "Armor", Type: "Boots", Description: "A pair of leather boots."},
	{Name: "Leather Gloves", Category: "Armor", Type: "Gloves", Description: "A pair of leather gloves."},
	{Name: "Padded Armor", Category: "Armor", Type: "Armor", Description: "AC: 11 + Dex modifier, Type: Light Armor, Disadvantage on Stealth"},
	{Name: "Leather Armor", Category: "Armor", Type: "Armor", Description: "AC: 11 + Dex modifier, Type: Light Armor"},
	{Name: "Studded Leather", Category: "Armor", Type: "Armor", Description: "AC: 12 + Dex modifier, Type: Light Armor"},
	{Name: "Hide Armor", Category: "Armor", Type: "Armor", Description: "AC: 12 + Dex modifier (max 2), Type: Medium Armor"},
	{Name: "Chain Shirt", Category: "Armor", Type: "Armor", Description: "AC: 13 + Dex modifier (max 2), Type: Medium Armor"},
	{Name: "Scale Mail", Category: "Armor", Type: "Armor", Description: "AC: 14 + Dex modifier (max 2), Type: Medium Armor, Disadvantage on Stealth"},
	{Name: "Breastplate", Category: "Armor", Type: "Armor", Description: "AC: 14 + Dex modifier (max 2), Type: Medium Armor"},
	{Name: "Half Plate", Category: "Armor", Type: "Armor", Description: "AC: 15 + Dex modifier (max 2), Type: Medium Armor, Disadvantage on Stealth"},
	{Name: "Ring Mail", Category: "Armor", Type: "Armor", Description: "AC: 14, Type: Heavy Armor, Disadvantage on Stealth"},
	{Name: "Chain Mail", Category: "Armor", Type: "Armor", Description: "AC: 16, Type: Heavy Armor, Disadvantage on Stealth"},
	{Name: "Splint", Category: "Armor", Type: "Armor", Description: "AC: 17, Type: Heavy Armor, Disadvantage on Stealth"},
	{Name: "Plate", Category: "Armor", Type: "Armor", Description: "AC: 18, Type: Heavy Armor, Disadvantage on Stealth"},
	{Name: "Shield", Category: "Armor", Type: "Armor", Description: "AC: +2"},
}

var meleeWeaponData = []Item{
	{Name: "Unarmed", Category: "Weapon", Type: "Melee", Description: "1 Bludgeoning", Properties: "Light", Options: "Attack"},
	{Name: "Rapier", Category: "Weapon", Type: "Melee", Description: "1d8 Piercing", Properties: "Finesse", Options: "Attack"},
	{Name: "Rapier +1", Category: "Weapon", Type: "Melee", Description: "1d8+1 Piercing", Properties: "Finesse", Options: "Attack"},
	{Name: "Rapier +2", Category: "Weapon", Type: "Melee", Description: "1d8+2 Piercing", Properties: "Finesse", Options: "Attack"},
	{Name: "Club", Category: "Weapon", Type: "Melee", Description: "1d4 Bludgeoning", Properties: "Light", Options: "Attack"},
	{Name: "Club +1", Category: "Weapon", Type: "Melee", Description: "1d4+1 Bludgeoning", Properties: "Light", Options: "Attack"},
	{Name: "Club +2", Category: "Weapon", Type: "Melee", Description: "1d4+2 Bludgeoning", Properties: "Light", Options: "Attack"},
	{Name: "Dagger", Category: "Weapon", Type: "Melee", Description: "1d4 Piercing", Properties: "Finesse|Light|Thrown (range 20/60)", Options: "Attack"},
	{Name: "Dagger +1", Category: "Weapon", Type: "Melee", Description: "1d4+1 Piercing", Properties: "Finesse|Light|Thrown (range 20/60)", Options: "Attack"},
	{Name: "Dagger +2", Category: "Weapon", Type: "Melee", Description: "1d4+2 Piercing", Properties: "Finesse|Light|Thrown (range 20/60)", Options: "Attack"},
	{Name: "Greatclub", Category: "Weapon", Type: "Melee", Description: "1d8 Bludgeoning", Properties: "Two-handed", Options: "Attack"},
	{Name: "Greatclub +1", Category: "Weapon", Type: "Melee", Description: "1d8+1 Bludgeoning", Properties: "Two-handed", Options: "Attack"},
	{Name: "Greatclub +2", Category: "Weapon", Type: "Melee", Description: "1d8+2 Bludgeoning", Properties: "Two-handed", Options: "Attack"},
	{Name: "Handaxe", Category: "Weapon", Type: "Melee", Description: "1d6 Slashing", Properties: "Light|Thrown (range 20/60)", Options: "Attack"},
	{Name: "Handaxe +1", Category: "Weapon", Type: "Melee", Description: "1d6+1 Slashing", Properties: "Light|Thrown (range 20/60)", Options: "Attack"},
	{Name: "Handaxe +2", Category: "Weapon", Type: "Melee", Description: "1d6+2 Slashing", Properties: "Light|Thrown (range 20/60)", Options: "Attack"},
	{Name: "Javelin", Category: "Weapon", Type: "Melee", Description: "1d6 Piercing", Properties: "Thrown (range 30/120)", Options: "Attack"},
	{Name: "Javelin +1", Category: "Weapon", Type: "Melee", Description: "1d6+1 Piercing", Properties: "Thrown (range 30/120)", Options: "Attack"},
	{Name: "Javelin +2", Category: "Weapon", Type: "Melee", Description: "1d6+2 Piercing", Properties: "Thrown (range 30/120)", Options: "Attack"},
	{Name: "Light Hammer", Category: "Weapon", Type: "Melee", Description: "1d4 Bludgeoning", Properties: "Light|Thrown (range 20/60)", Options: "Attack"},
	{Name: "Light Hammer +1", Category: "Weapon", Type: "Melee", Description: "1d4+1 Bludgeoning", Properties: "Light|Thrown (range 20/60)", Options: "Attack"},
	{Name: "Light Hammer +2", Category: "Weapon", Type: "Melee", Description: "1d4+2 Bludgeoning", Properties: "Light|Thrown (range 20/60)", Options: "Attack"},
	{Name: "Mace", Category: "Weapon", Type: "Melee", Description: "1d6 Bludgeoning", Properties: "", Options: "Attack"},
	{Name: "Mace +1", Category: "Weapon", Type: "Melee", Description: "1d6+1 Bludgeoning", Properties: "", Options: "Attack"},
	{Name: "Mace +2", Category: "Weapon", Type: "Melee", Description: "1d6+2 Bludgeoning", Properties: "", Options: "Attack"},
	{Name: "Quarterstaff", Category: "Weapon", Type: "Melee", Description: "1d6 Bludgeoning", Properties: "Versatile (1d8)", Options: "Attack"},
	{Name: "Quarterstaff +1", Category: "Weapon", Type: "Melee", Description: "1d6+1 Bludgeoning", Properties: "Versatile (1d8)", Options: "Attack"},
	{Name: "Quarterstaff +2", Category: "Weapon", Type: "Melee", Description: "1d6+2 Bludgeoning", Properties: "Versatile (1d8)", Options: "Attack"},
	{Name: "Sickle", Category: "Weapon", Type: "Melee", Description: "1d4 Slashing", Properties: "Light", Options: "Attack"},
	{Name: "Sickle +1", Category: "Weapon", Type: "Melee", Description: "1d4+1 Slashing", Properties: "Light", Options: "Attack"},
	{Name: "Sickle +2", Category: "Weapon", Type: "Melee", Description: "1d4 Slashing", Properties: "Light", Options: "Attack"},
	{Name: "Spear", Category: "Weapon", Type: "Melee", Description: "1d6 Piercing", Properties: "Thrown (range 20/60)|Versatile (1d8)", Options: "Attack"},
	{Name: "Spear +1", Category: "Weapon", Type: "Melee", Description: "1d6+1 Piercing", Properties: "Thrown (range 20/60)|Versatile (1d8)", Options: "Attack"},
	{Name: "Spear +2", Category: "Weapon", Type: "Melee", Description: "1d6+2 Piercing", Properties: "Thrown (range 20/60)|Versatile (1d8)", Options: "Attack"},
	{Name: "Battleaxe", Category: "Weapon", Type: "Melee", Description: "1d8 Slashing", Properties: "Versatile (1d10)", Options: "Attack"},
	{Name: "Battleaxe +1", Category: "Weapon", Type: "Melee", Description: "1d8+1 Slashing", Properties: "Versatile (1d10)", Options: "Attack"},
	{Name: "Battleaxe +2", Category: "Weapon", Type: "Melee", Description: "1d8+2 Slashing", Properties: "Versatile (1d10)", Options: "Attack"},
	{Name: "Flail", Category: "Weapon", Type: "Melee", Description: "1d8 Bludgeoning", Properties: "", Options: "Attack"},
	{Name: "Flail +1", Category: "Weapon", Type: "Melee", Description: "1d8+1 Bludgeoning", Properties: "", Options: "Attack"},
	{Name: "Flail +2", Category: "Weapon", Type: "Melee", Description: "1d8+2 Bludgeoning", Properties: "", Options: "Attack"},
	{Name: "Glaive", Category: "Weapon", Type: "Melee", Description: "1d10 Slashing", Properties: "Heavy|Reach|Two-Handed", Options: "Attack"},
	{Name: "Glaive +1", Category: "Weapon", Type: "Melee", Description: "1d10+1 Slashing", Properties: "Heavy|Reach|Two-Handed", Options: "Attack"},
	{Name: "Glaive +2", Category: "Weapon", Type: "Melee", Description: "1d10+2 Slashing", Properties: "Heavy|Reach|Two-Handed", Options: "Attack"},
	{Name: "Greataxe", Category: "Weapon", Type: "Melee", Description: "1d12 Slashing", Properties: "Heavy|Two-Handed", Options: "Attack"},
	{Name: "Greataxe +1", Category: "Weapon", Type: "Melee", Description: "1d12+1 Slashing", Properties: "Heavy|Two-Handed", Options: "Attack"},
	{Name: "Greataxe +2", Category: "Weapon", Type: "Melee", Description: "1d12+2 Slashing", Properties: "Heavy|Two-Handed", Options: "Attack"},
	{Name: "Greatsword", Category: "Weapon", Type: "Melee", Description: "2d6 Slashing", Properties: "Heavy|Two-Handed", Options: "Attack"},
	{Name: "Greatsword +1", Category: "Weapon", Type: "Melee", Description: "2d6+1 Slashing", Properties: "Heavy|Two-Handed", Options: "Attack"},
	{Name: "Greatsword +2", Category: "Weapon", Type: "Melee", Description: "2d6+2 Slashing", Properties: "Heavy|Two-Handed", Options: "Attack"},
	{Name: "Halberd", Category: "Weapon", Type: "Melee", Description: "1d10 Slashing", Properties: "Heavy|Reach|Two-Handed", Options: "Attack"},
	{Name: "Halberd +1", Category: "Weapon", Type: "Melee", Description: "1d10+1 Slashing", Properties: "Heavy|Reach|Two-Handed", Options: "Attack"},
	{Name: "Halberd +2", Category: "Weapon", Type: "Melee", Description: "1d10+2 Slashing", Properties: "Heavy|Reach|Two-Handed", Options: "Attack"},
	{Name: "Lance", Category: "Weapon", Type: "Melee", Description: "1d12 Piercing", Properties: "Reach|Special", Options: "Attack"},
	{Name: "Lance +1", Category: "Weapon", Type: "Melee", Description: "1d12 Piercing", Properties: "Reach|Special", Options: "Attack"},
	{Name: "Lance +2", Category: "Weapon", Type: "Melee", Description: "1d12 Piercing", Properties: "Reach|Special", Options: "Attack"},
	{Name: "Longsword", Category: "Weapon", Type: "Melee", Description: "1d8 Slashing", Properties: "Versatile (1d10)", Options: "Attack"},
	{Name: "Longsword +1", Category: "Weapon", Type: "Melee", Description: "1d8+1 Slashing", Properties: "Versatile (1d10)", Options: "Attack"},
	{Name: "Longsword +2", Category: "Weapon", Type: "Melee", Description: "1d8+2 Slashing", Properties: "Versatile (1d10)", Options: "Attack"},
	{Name: "Maul", Category: "Weapon", Type: "Melee", Description: "2d6 Bludgeoning", Properties: "Heavy|Two-Handed", Options: "Attack"},
	{Name: "Maul +1", Category: "Weapon", Type: "Melee", Description: "2d6+1 Bludgeoning", Properties: "Heavy|Two-Handed", Options: "Attack"},
	{Name: "Maul +2", Category: "Weapon", Type: "Melee", Description: "2d6+2 Bludgeoning", Properties: "Heavy|Two-Handed", Options: "Attack"},
	{Name: "Morningstar", Category: "Weapon", Type: "Melee", Description: "1d8 Piercing", Properties: "", Options: "Attack"},
	{Name: "Morningstar +1", Category: "Weapon", Type: "Melee", Description: "1d8+1 Piercing", Properties: "", Options: "Attack"},
	{Name: "Morningstar +2", Category: "Weapon", Type: "Melee", Description: "1d8+2 Piercing", Properties: "", Options: "Attack"},
	{Name: "Pike", Category: "Weapon", Type: "Melee", Description: "1d10 Piercing", Properties: "Heavy|Reach|Two-Handed", Options: "Attack"},
	{Name: "Pike +1", Category: "Weapon", Type: "Melee", Description: "1d10+1 Piercing", Properties: "Heavy|Reach|Two-Handed", Options: "Attack"},
	{Name: "Pike +2", Category: "Weapon", Type: "Melee", Description: "1d10+2 Piercing", Properties: "Heavy|Reach|Two-Handed", Options: "Attack"},
	{Name: "Rapier", Category: "Weapon", Type: "Melee", Description: "1d8 Piercing", Properties: "Finesse", Options: "Attack"},
	{Name: "Rapier +1", Category: "Weapon", Type: "Melee", Description: "1d8+1 Piercing", Properties: "Finesse", Options: "Attack"},
	{Name: "Rapier +2", Category: "Weapon", Type: "Melee", Description: "1d8+2 Piercing", Properties: "Finesse", Options: "Attack"},
	{Name: "Scimitar", Category: "Weapon", Type: "Melee", Description: "1d6 Slashing", Properties: "Finesse|Light", Options: "Attack"},
	{Name: "Scimitar +1", Category: "Weapon", Type: "Melee", Description: "1d6+1 Slashing", Properties: "Finesse|Light", Options: "Attack"},
	{Name: "Scimitar +2", Category: "Weapon", Type: "Melee", Description: "1d6+2 Slashing", Properties: "Finesse|Light", Options: "Attack"},
	{Name: "Shortsword", Category: "Weapon", Type: "Melee", Description: "1d6 Piercing", Properties: "Finesse|Light", Options: "Attack"},
	{Name: "Shortsword +1", Category: "Weapon", Type: "Melee", Description: "1d6+1 Piercing", Properties: "Finesse|Light", Options: "Attack"},
	{Name: "Shortsword +2", Category: "Weapon", Type: "Melee", Description: "1d6+2 Piercing", Properties: "Finesse|Light", Options: "Attack"},
	{Name: "Trident", Category: "Weapon", Type: "Melee", Description: "1d6 Piercing", Properties: "Thrown (range 20/60)|Versatile (1d8)", Options: "Attack"},
	{Name: "Trident +1", Category: "Weapon", Type: "Melee", Description: "1d6+1 Piercing", Properties: "Thrown (range 20/60)|Versatile (1d8)", Options: "Attack"},
	{Name: "Trident +2", Category: "Weapon", Type: "Melee", Description: "1d6+2 Piercing", Properties: "Thrown (range 20/60)|Versatile (1d8)", Options: "Attack"},
	{Name: "War pick", Category: "Weapon", Type: "Melee", Description: "1d8 Piercing", Properties: "", Options: "Attack"},
	{Name: "War pick +1", Category: "Weapon", Type: "Melee", Description: "1d8+1 Piercing", Properties: "", Options: "Attack"},
	{Name: "War pick +2", Category: "Weapon", Type: "Melee", Description: "1d8+2 Piercing", Properties: "", Options: "Attack"},
	{Name: "Warhammer", Category: "Weapon", Type: "Melee", Description: "1d8 Bludgeoning", Properties: "Versatile (1d10)", Options: "Attack"},
	{Name: "Warhammer +1", Category: "Weapon", Type: "Melee", Description: "1d8+1 Bludgeoning", Properties: "Versatile (1d10)", Options: "Attack"},
	{Name: "Warhammer +2", Category: "Weapon", Type: "Melee", Description: "1d8+2 Bludgeoning", Properties: "Versatile (1d10)", Options: "Attack"},
	{Name: "Whip", Category: "Weapon", Type: "Melee", Description: "1d4 Slashing", Properties: "Finesse|Reach", Options: "Attack"},
	{Name: "Whip +1", Category: "Weapon", Type: "Melee", Description: "1d4+1 Slashing", Properties: "Finesse|Reach", Options: "Attack"},
	{Name: "Whip +2", Category: "Weapon", Type: "Melee", Description: "1d4+2 Slashing", Properties: "Finesse|Reach", Options: "Attack"},
}

var rangedWeaponData = []Item{
	{Name: "Light Crossbow", Category: "Weapon", Type: "Ranged", Description: "1d8 Piercing", Properties: "Ammunition (range 80/320)|Loading|Two-Handed", Options: "Ranged Attack"},
	{Name: "Light Crossbow +1", Category: "Weapon", Type: "Ranged", Description: "1d8+1 Piercing", Properties: "Ammunition (range 80/320)|Loading|Two-Handed", Options: "Ranged Attack"},
	{Name: "Light Crossbow +2", Category: "Weapon", Type: "Ranged", Description: "1d8+2 Piercing", Properties: "Ammunition (range 80/320)|Loading|Two-Handed", Options: "Ranged Attack"},
	{Name: "Dart", Category: "Weapon", Type: "Ranged", Description: "1d4 Piercing", Properties: "Finesse|Thrown (range 20/60)", Options: "Ranged Attack"},
	{Name: "Dart +1", Category: "Weapon", Type: "Ranged", Description: "1d4+1 Piercing", Properties: "Finesse|Thrown (range 20/60)", Options: "Ranged Attack"},
	{Name: "Dart +2", Category: "Weapon", Type: "Ranged", Description: "1d4 Piercing", Properties: "Finesse|Thrown (range 20/60)", Options: "Ranged Attack"},
	{Name: "Shortbow", Category: "Weapon", Type: "Ranged", Description: "1d6 Piercing Damage", Properties: "Ammunition|Range|Two-Handed", Options: "Ranged Attack"},
	{Name: "Shortbow +1", Category: "Weapon", Type: "Ranged", Description: "1d6+1 Piercing Damage", Properties: "Ammunition|Range|Two-Handed", Options: "Ranged Attack"},
	{Name: "Shortbow +2", Category: "Weapon", Type: "Ranged", Description: "1d6+2 Piercing Damage", Properties: "Ammunition|Range|Two-Handed", Options: "Ranged Attack"},
	{Name: "Sling", Category: "Weapon", Type: "Ranged", Description: "1d4 Bludgeoning", Properties: "Ammunition (range 30/120)", Options: "Ranged Attack"},
	{Name: "Sling +1", Category: "Weapon", Type: "Ranged", Description: "1d4+1 Bludgeoning", Properties: "Ammunition (range 30/120)", Options: "Ranged Attack"},
	{Name: "Sling +2", Category: "Weapon", Type: "Ranged", Description: "1d4+2 Bludgeoning", Properties: "Ammunition (range 30/120)", Options: "Ranged Attack"},
	{Name: "Blowgun", Category: "Weapon", Type: "Ranged", Description: "1 Piercing", Properties: "Ammunition (range 25/100)|Loading", Options: "Ranged Attack"},
	{Name: "Blowgun +1", Category: "Weapon", Type: "Ranged", Description: "1 Piercing", Properties: "Ammunition (range 25/100)|Loading", Options: "Ranged Attack"},
	{Name: "Blowgun +2", Category: "Weapon", Type: "Ranged", Description: "1 Piercing", Properties: "Ammunition (range 25/100)|Loading", Options: "Ranged Attack"},
	{Name: "Hand Crossbow", Category: "Weapon", Type: "Ranged", Description: "1d6 Piercing", Properties: "Ammunition (range 30/120)|Light|Loading", Options: "Ranged Attack"},
	{Name: "Hand Crossbow +1", Category: "Weapon", Type: "Ranged", Description: "1d6+1 Piercing", Properties: "Ammunition (range 30/120)|Light|Loading", Options: "Ranged Attack"},
	{Name: "Hand Crossbow +2", Category: "Weapon", Type: "Ranged", Description: "1d6+2 Piercing", Properties: "Ammunition (range 30/120)|Light|Loading", Options: "Ranged Attack"},
	{Name: "Heavy Crossbow", Category: "Weapon", Type: "Ranged", Description: "1d10 Piercing", Properties: "Ammunition (range 100/400)|heavy|Loading|Two-Handed", Options: "Ranged Attack"},
	{Name: "Heavy Crossbow +1", Category: "Weapon", Type: "Ranged", Description: "1d10+1 Piercing", Properties: "Ammunition (range 100/400)|heavy|Loading|Two-Handed", Options: "Ranged Attack"},
	{Name: "Heavy Crossbow +2", Category: "Weapon", Type: "Ranged", Description: "1d10+2 Piercing", Properties: "Ammunition (range 100/400)|heavy|Loading|Two-Handed", Options: "Ranged Attack"},
	{Name: "Longbow", Category: "Weapon", Type: "Ranged", Description: "1d8 Piercing", Properties: "Ammunition (range 150/600)|heavy|Two-Handed", Options: "Ranged Attack"},
	{Name: "Longbow +1", Category: "Weapon", Type: "Ranged", Description: "1d8+1 Piercing", Properties: "Ammunition (range 150/600)|heavy|Two-Handed", Options: "Ranged Attack"},
	{Name: "Longbow +2", Category: "Weapon", Type: "Ranged", Description: "1d8+2 Piercing", Properties: "Ammunition (range 150/600)|heavy|Two-Handed", Options: "Ranged Attack"},
	{Name: "Net", Category: "Weapon", Type: "Ranged", Description: "0", Properties: "Special|Thrown (range 5/15)", Options: "Ranged Attack"},
}

var itemData = []Item{
	{Name: "Potion of Healing", Category: "Item", Type: "Healing", Description: "You regain 2d4 + 2 hit points when you drink this potion."},
	{Name: "Potion of Greater Healing", Category: "Item", Type: "Healing", Description: "You regain 4d4 + 4 hit points when you drink this potion."},
	{Name: "Potion of Superior Healing", Category: "Item", Type: "Healing", Description: "You regain 8d4 + 8 hit points when you drink this potion."},
	{Name: "Potion of Supreme Healing", Category: "Item", Type: "Healing", Description: "You regain 10d4 + 20 hit points when you drink this potion."},
	{Name: "Potion of Poison", Category: "Item", Type: "Damage", Description: "You must succeed on a DC 13 Constitution saving throw or take 3d6 poison damage and become poisoned for 1 minute. If the saving throw is successful, the creature takes half damage and isn't poisoned."},
	{Name: "Potion of Fire Breath", Category: "Item", Type: "Damage", Description: "After drinking this potion, you can use a bonus action to exhale fire at a target within 30 feet of you. The target must make a DC 13 Dexterity saving throw, taking 4d6 fire damage on a failed save, or half as much damage on a successful one. The effect ends after you exhale the fire three times or when 1 hour has passed."},
	{Name: "Potion of Resistance", Category: "Item", Type: "Buff", Description: "When you drink this potion, choose acid, cold, fire, lightning, or thunder. The potion grants you resistance to that damage type for 1 hour."},
	{Name: "Potion of Animal Friendship", Category: "Item", Type: "Buff", Description: "When you drink this potion, you can cast the animal friendship spell (save DC 13) for 1 hour at will. Agitating this muddy liquid brings little bits into view: a fish scale, a hummingbird tongue, a cat claw, or a squirrel hair."},
}

var itemsData = [][]Item{
	armorData,
	itemData,
	meleeWeaponData,
	rangedWeaponData,
}
